### PR TITLE
Created base React client using Vite

### PR DESCRIPTION
**Pull request by joshluca98**
Basic client setup configured.

### CODE REVIEW

**Review by Sillor — APPROVED** [review]
Works good

**Review by Ric-KL — APPROVED** [review]
looks good

**Review by Ric-KL — APPROVED** [review]
looks good

**Review by Ric-KL — DISMISSED** [review]
yes

**Review by Sillor — APPROVED** [review]
Good

**Review by nlawler1737 — APPROVED** [review]
looks good

**Review by Ric-KL — APPROVED** [review]
Yes

**Pull request merged**
